apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  labels:
    app: user-service-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      name: user-service
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service-container
          image: user-service:1.0.2
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  key: PORT
                  name: user-service-config
            - name: MONGODB_HOST
              valueFrom:
                configMapKeyRef:
                  key: MONGODB_HOST
                  name: user-service-config
            - name: MONGODB_PORT
              valueFrom:
                configMapKeyRef:
                  key: MONGODB_PORT
                  name: user-service-config
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
